name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # Same as used in AWS Lambda
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r discord_handler/requirements.txt
        pip install -r discord_handler/dev_requirements.txt
    - name: Run tests
      run: |
        python discord_handler/test_filmbot.py -v
